---
- hosts: all

  pre_tasks:
    - name: Update APT cache
      apt: update_cache=yes

  roles:
    - { role: "gunicorn.example" }

  vars:
    gunicorn_bind: "0.0.0.0:8000"
    gunicorn_app_dir: /var/lib/gunicorn
    gunicorn_wsgi: hello_world
    gunicorn_loglevel: "debug"
    gunicorn_accesslog: False
    gunicorn_errorlog: "-"
    gunicorn_reload: True
    gunicorn_start_on: "vagrant-mounted"
